### PR TITLE
Making suggested change in issue 64

### PR DESCRIPTION
**Pull request by dannyjgibson**
#64

### CODE REVIEW

**Review by polishmatt — APPROVED** [review]
Change looks good but this will need an update to version (2.2.1) in these two places before being released:
https://github.com/jwplayer/jwplatform-py/blob/master/jwplatform/version.py#L2
https://github.com/jwplayer/jwplatform-py/blob/master/CHANGES.rst

**Comment by dylancaponi** [comment]
What's the next step to getting this into a release?

**Comment by polishmatt** [comment]
This is the pipeline: https://buildkite.com/jwplayer/jwplatform/builds?branch=develop
There have been other deploys to production since this was merged so it seems this is already out in prod.

**Comment by dylancaponi** [comment]
Thanks for the quick reply.

I cannot access that pipeline link.

I see the change it in the master branch but _not_ in the most recent release from pip.
```
% pip freeze
jwplatform==2.1.3
```

contents of site-packages/jwplatform/client.py:
```
class _ThumbnailClient(_ResourceClient):
    _resource_name = "thumbnails"
    _id_name = "thumbnail_id"
```

**Pull request merged**
